* se actualiza el readme * se coloca comprobacion de root

diff --git a/securegen b/securegen
--- a/securegen
+++ b/securegen
@@ -3,6 +3,11 @@
 # Licence: GPL-2
 LC_ALL=C
 
+if [[ "$EUID" = "0" ]]; then
+	echo -e "\e[00;31mERROR: No debe ser root.\e[00m"
+	exit 1
+fi
+
 if [[ -z $1 ]]; then
 	echo "USO: ./securegen nombre apellido su@correo.com clave"
 	exit 1
